version: '3.8'

services:
  star-chart-tracker:
    build: .
    ports:
      - "4000:4000"
    container_name: star-chart-tracker
    volumes:
      - star_charts_data:/app/data
    environment:
      - NODE_ENV=production

volumes:
  star_charts_data: