version: '3.8'

services:
  star-chart-tracker:
    build: .
    ports:
      - "0.0.0.0:4000:4000"
    container_name: star-chart-tracker
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production